strings:
  appName: ATD Shoplist
  title: TweedleDo Shopping List
  description: artyhedgehog's TweedleDo Shopping List app
  searchBar.placeholder: What do I need to buy?
  footer.archiveCompleted: Check out
  todoItem.unarchive: Out of stock
  menu.data: Data export/import
  menu.tweedledo: To TweedleDo website

lists:
  - id: groceries
    icon: IconApple
    label: Food
  - id: pharmacy
    icon: IconPill
    label: Pharmacy
  - id: misc
    icon: IconTools
    label: Misc
  - id: tea
    icon: IconCoffee # =(
    label: Tea
  - id: pets
    icon: IconCat
    label: Pets
  - id: books
    icon: IconBooks
    label: Books

states:
  - id: stock
    label: Stock
    filter: archived
    hash: '#/archived'
  - id: shop
    label: Shop!
    filter: all
    hash: '#/'
  - id: buy
    label: To buy
    filter: active
    hash: '#/active'
  - id: cart
    label: Cart
    filter: completed
    hash: '#/completed'
filters:
  all:
    value: archived eq false
  active:
    value: completed eq false and archived eq false
  completed:
    value: completed eq true and archived eq false
  archived:
    value: archived eq true

